services:
  db:
    image: postgres:16-alpine
    container_name: ttt-postgres
    env_file:
      - .env.api.production # или .env.api.development
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ports:
      - "5432:5432"   # опционально, можно убрать в проде
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ttt-app
    env_file: .env.api.production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pg_data:
